//
//  SNTabBarItem.h
//  SNTabBarDemo
//
//  Created by ShawnWong on 2022/1/5.
//

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface SNTabBarItem : UIButton

/* The unselected image is autogenerated from the image argument. The selected image
 is autogenerated from the selectedImage if provided and the image argument otherwise.
 To prevent system coloring, provide images with UIImageRenderingModeAlwaysOriginal (see UIImage.h)
 */
- (instancetype)initWithImage:(UIImage *)image selectedImage:(UIImage *)selectedImage;

@property(nullable, nonatomic,strong) UIImage   *image;
@property(nullable, nonatomic,strong) UIImage   *selectedImage;

@property(nonatomic)                  UIEdgeInsets imageInsets;  // default is UIEdgeInsetsMake(-49, 0, 0, 0);

@end

NS_ASSUME_NONNULL_END
